### ISSUE TITLE
`is_flip` better variable name

### ISSUE THREAD

**Issue by bearomorphism** [pooiscoding/Flappy_Bird#1]
It'd be better to name this `need_flip` or `is_flip_needed`.

如果不一定要 `boolean` 的話， direction: 'up' or 'down' 應該更清楚

https://github.com/pooiscoding/Flappy_Bird/blob/530f88c4d264fa1db289edd947ec518e4e9174a8/Pipes.py#L13

**Comment by pooiscoding** [comment]
OK, I fixed it
