### ISSUE TITLE
Reusing variable is not a good practice

### ISSUE THREAD

**Issue by bearomorphism** [pooiscoding/Flappy_Bird#2]
建議把第二個 image 改成 `scaled_image` 之類的，在這個狀況下重複使用變數不是一個好的實作

https://github.com/pooiscoding/Flappy_Bird/blob/530f88c4d264fa1db289edd947ec518e4e9174a8/Helper.py#L4-L7

**Comment by pooiscoding** [comment]
OK, I fixed it
